#!/bin/bash

echo "🍪 Elva AI - Cookie Capture Setup Guide"
echo "======================================="
echo ""
echo "Since you're in a containerized environment, here's how to capture cookies:"
echo ""
echo "📋 STEP-BY-STEP INSTRUCTIONS:"
echo ""
echo "1️⃣  SETUP (One-time only):"
echo "   - Install Python 3.11+ on your local machine"
echo "   - Install required packages:"
echo "     pip install playwright python-dotenv cryptography"
echo "     playwright install chromium"
echo ""
echo "2️⃣  DOWNLOAD SCRIPTS:"
echo "   Copy these files to your local machine:"
echo "   - manual_cookie_capture.py"
echo "   - cookie_manager.py"
echo ""
echo "3️⃣  RUN COOKIE CAPTURE:"
echo "   python manual_cookie_capture.py"
echo ""
echo "4️⃣  TRANSFER COOKIES:"
echo "   After capturing cookies locally:"
echo "   - Copy the 'cookies' directory to your Elva AI server"
echo "   - Or use the API endpoints to verify the cookies are working"
echo ""
echo "🎯 RECOMMENDED SERVICES TO START WITH:"
echo "   1. LinkedIn (most useful for professional automation)"
echo "   2. Gmail (if you use Google Login)"
echo ""
echo "📞 NEED HELP? Check the detailed guide at:"
echo "   /app/backend/COOKIE_GUIDE.md"
echo ""
echo "🔒 SECURITY NOTE:"
echo "   - Cookies are encrypted and stored securely"
echo "   - Valid for 30 days before auto-expiry"
echo "   - Only accessible by your Elva AI instance"