import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';

const ApprovalModal = ({ 
  showApprovalModal, 
  pendingApproval, 
  editMode, 
  setEditMode, 
  editedData, 
  setEditedData,
  handleApproval,
  renderEditForm 
}) => {
  if (!showApprovalModal || !pendingApproval) return null;

  return (
    <AnimatePresence>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4"
      >
        <motion.div
          initial={{ scale: 0.9, opacity: 0 }}
          animate={{ scale: 1, opacity: 1 }}
          exit={{ scale: 0.9, opacity: 0 }}
          className="bg-gray-800 rounded-xl p-6 max-w-2xl w-full max-h-[80vh] overflow-y-auto border border-gray-600"
        >
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-xl font-bold text-white flex items-center">
              <span className="mr-2">🤖</span>
              Action Approval Required
            </h3>
            <div className="flex items-center space-x-2">
              <button
                onClick={() => setEditMode(!editMode)}
                className="px-3 py-1 bg-blue-600 text-white rounded text-sm hover:bg-blue-700 transition-colors"
              >
                {editMode ? 'View' : 'Edit'}
              </button>
            </div>
          </div>

          <div className="mb-4 p-3 bg-blue-900/20 rounded-lg border border-blue-500/30">
            <p className="text-sm text-blue-300 mb-2">
              ⚠️ This action was generated by AI. Please review the details before approving.
            </p>
            <div className="text-sm text-gray-300">
              <strong>Detected Intent:</strong> {pendingApproval.intent_data?.intent?.replace('_', ' ').toUpperCase()}
            </div>
          </div>

          {editMode ? (
            renderEditForm()
          ) : (
            <div className="space-y-4">
              <h4 className="text-sm font-medium text-blue-300 flex items-center">
                <span className="mr-2">📋</span>
                Action Details:
              </h4>
              <div className="bg-gray-900/40 p-4 rounded-lg border border-gray-600/30">
                <pre className="text-sm text-gray-300 whitespace-pre-wrap font-mono">
                  {JSON.stringify(editedData || pendingApproval.intent_data, null, 2)}
                </pre>
              </div>
            </div>
          )}

          <div className="flex justify-end space-x-3 mt-6">
            <button
              onClick={() => handleApproval(false)}
              className="px-6 py-2 bg-gray-600 text-white rounded-lg hover:bg-gray-700 transition-colors"
            >
              Cancel
            </button>
            <button
              onClick={() => handleApproval(true)}
              className="px-6 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors"
            >
              Approve
            </button>
          </div>
        </motion.div>
      </motion.div>
    </AnimatePresence>
  );
};

export default ApprovalModal;